docker-build:
  # Use the official docker image.
  image: docker:27-cli
  stage: build
  services:
    - name: docker:27-dind
      command: ["--tls=false"]
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - >
      docker build --pull
      --build-arg NEXT_PUBLIC_FIREBASE_API_KEY="$NEXT_PUBLIC_FIREBASE_API_KEY"
      --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
      --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID="$NEXT_PUBLIC_FIREBASE_PROJECT_ID"
      --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
      --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
      --build-arg NEXT_PUBLIC_FIREBASE_APP_ID="$NEXT_PUBLIC_FIREBASE_APP_ID"
      -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
deploy:
  stage: deploy
  script:
    - |
      echo "Webhook: $WEBHOOK"
      apk add --no-cache curl
      curl --request GET --url $WEBHOOK --header 'Authorization: Bearer 1|ii0BGN6a4jpEpU88y5o6cbSxjCoaKoV1bsBoYZEo6c4ed2c2'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $WEBHOOK
deploy_dev:
  stage: deploy
  script:
    - |
      echo "Webhook: $WEBHOOK_DEV"
      apk add --no-cache curl
      curl --request GET --url $WEBHOOK_DEV --header 'Authorization: Bearer 1|ii0BGN6a4jpEpU88y5o6cbSxjCoaKoV1bsBoYZEo6c4ed2c2'
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" && $WEBHOOK_DEV

